# Generated by Django 4.2.6 on 2023-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculateexpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total_participants', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
